### ISSUE TITLE
add windows platform support

### ISSUE THREAD

**Issue by tbsmanish** [riccardo-lomazzi/camera_macos#1]
combine https://pub.dev/packages/camera_windows with this package and make a new desktop_camera package. Even though I would like to help with that only functionality will be capturing images and videos. it's complicated to use two packages for the same functionality

**Comment by riccardo-lomazzi** [comment]
Hi @tbsmanish sorry for the late response.

It's a great suggestion that I've considered while developing this plugin, unfortunately I couldn't make out the structure of the official `camera` plugin (for which `camera_windows` is an interface) and took quite a bit replicate on `macOS`, so I've preferred to redo the entire thing and implement the basic functionalities.
