### ISSUE TITLE
support mirror flip camera

### ISSUE THREAD

**Issue by gsmlg** [riccardo-lomazzi/camera_macos#10]
Could you support mirror flip camera?

**Comment by Knightro63** [comment]
Hi @gsmlg,

Can you use `TransformScale` to view the image/video flipped or does it need to be done for saving the image/video?

Let me know.

Thanks

**Comment by gsmlg** [comment]
> Hi @gsmlg,
> 
> Can you use `TransformScale` to view the image/video flipped or does it need to be done for saving the image/video?
> 
> Let me know.
> 
> Thanks

@Knightro63 

Hi there,

Use `TransformScale` does not works well on this.

Make the video output not mirror-flip is useful when use a *capture card*.

This featurehas been implemented in https://github.com/gsmlg-dev/camera_macos/commit/261dce200e0e05fd8c805504d5455e840c3f1ab0

**Comment by Knightro63** [comment]
Hi @gsmlg,

If you do a pull request I am sure @riccardo-lomazzi will probably accept it.

Thanks for updating this package any new feature always helps.

**Comment by gsmlg** [comment]
> Hi @gsmlg,
> 
> If you do a pull request I am sure @riccardo-lomazzi will probably accept it.
> 
> Thanks for updating this package any new feature always helps.

Hi @Knightro63 

Add pull request https://github.com/riccardo-lomazzi/camera_macos/pull/11
