### ISSUE TITLE
Use without audio

### ISSUE THREAD

**Issue by sneurlax** [riccardo-lomazzi/camera_macos#12]
Hi!  Can we use this without audio nor the audio permission?  I just want to scan QR codes :)

Thanks!

I can help implement this feature if you direct me.

**Comment by Knightro63** [comment]
Hi @sneurlax,

Yes you can use this repo with out audio and audio permissions. [Here](https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_scanner) is an example of this working.

**Comment by riccardo-lomazzi** [comment]
Hi @sneurlax ,

yes you can, just skip the configuration settings in which you set the audio permissions.
So, skip these:

```
<key>com.apple.security.device.audio-input</key>
<true/>
```

and

```
<key>NSMicrophoneUsageDescription</key>
<string>your usage description here</string>
```

and set 
`enableAudio: false` when initializing the `CameraMacOSView` widget.

Let me know if it works for you.
