### ISSUE TITLE
Why this is not merged with official camera package?

### ISSUE THREAD

**Issue by scognito** [riccardo-lomazzi/camera_macos#13]
I'm using this package and works well, I'm also using image stream for facial recognition with wonderful result. 
It is a pity it is not merged, thank you for all the work!

**Comment by Knightro63** [comment]
Hi @scognito,

Which part needs to be merged? 

I think this is just a package for camera use only, similar to flutter teams version of camera for the other platforms.

**Comment by scognito** [comment]
Merged into the official camera package I mean

**Comment by Knightro63** [comment]
Hi @scognito,

I am sorry for the misunderstanding. I am unsure what the flutter team's plans are at the moment but I believe they are currently working on their own version [here](https://github.com/stuartmorgan/packages/tree/macos-camera).

**Comment by riccardo-lomazzi** [comment]
Hi @scognito 
I've had to implement the Camera framework on a work project, since there wasn't an official camera package by Flutter, I had to put something together. I've decided to make it publicly available to everyone, hoping that it would help someone.
