### ISSUE TITLE
stopImageStream doesn't work

### ISSUE THREAD

**Issue by scognito** [riccardo-lomazzi/camera_macos#14]
When I call 
`await stopImageStream` and then `isStreamingImageData`, I get always true.
After digging a bit I found that the function `stopImageStream` does not set `events` to null.

I modified the code to this:
```dart
  @override
  Future<void> stopImageStream() async {
    await events?.cancel();
    events = null; // added this
  }
```

It works, but sometimes the app crashes on `CameraMacosPlugin.swift` with this error:

_camera_macos/CameraMacosPlugin.swift:117: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value_+

I don't have time to fix this though

**Comment by Knightro63** [comment]
Hi @scognito,

Thanks for reporting this issue. I will take a look and see if I can update it to address this issue.

**Comment by scognito** [comment]
You can add the line I added. I didn't make a PR just because there is still the crash on CameraMacosPlugin.swift.
It should be trivial to fix though

**Comment by riccardo-lomazzi** [comment]
I've added the stream cancelling function and changed the function signature to support error handling. It should be released in the next update. Thank you!
