### ISSUE TITLE
stream support

### ISSUE THREAD

**Issue by wownsdl13** [riccardo-lomazzi/camera_macos#3]
are you planning to support stream of video?? :)

**Comment by riccardo-lomazzi** [comment]
> are you planning to support stream of video?? :)

Hello,

do you mean implementing an image buffer, that returns images within a `Stream`?
If so, this functionality isn't currently planned, but I can start researching into it.

**Comment by wownsdl13** [comment]
> > are you planning to support stream of video?? :)
> 
> Hello,
> 
> do you mean implementing an image buffer, that returns images within a `Stream`? If so, this functionality isn't currently planned, but I can start researching into it.

yes exactly !!

I'm struggling with that so I can't wait for that.

thank you so much and have a nice day ;)

**Comment by riccardo-lomazzi** [comment]
The new `startImageStream` function has been deployed with the new `0.0.7` release.
