### ISSUE TITLE
My macos can't open the camera

### ISSUE THREAD

**Issue by zengchao928** [riccardo-lomazzi/camera_macos#5]
Why I can turn on the camera by running your demo directly, but when I copy your code into my project, videoDevices is always 0，The code is completely copied, and the permissions are also given！

**Comment by riccardo-lomazzi** [comment]
Hello!
Could you please post the code you're trying to run?

**Comment by sunilguptasg** [comment]
Hi, add the following to these files: (under macos/Runner)
DebugProfile.entitlements
Release.entitlements

	<key>com.apple.security.device.camera</key>
	<true/>
	<key>com.apple.security.device.microphone</key>
	<true/>

I spent hours to get this fix, and I believe it should be added to documentation.

**Comment by riccardo-lomazzi** [comment]
Added.
